version: '3.8'

services:
  backend:
    build:
      context: ./batch-processor
    ports:
      - "5000:5000"
    container_name: backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    container_name: frontend
